services:
  webshop-db:
    image: postgres:16-alpine
    container_name: webshop-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_webshop_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_webshop_data: 
