-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TYPE public.estado_pedido AS ENUM
    ('pendiente', 'pagado', 'enviado', 'cerrado', 'anulado');

CREATE TYPE public.tipo_alergeno AS ENUM
    ('gluten', 'crustaceos', 'huevos', 'pescado', 'cacahuetes', 'soja', 'lacteos', 'frutos_casacara', 'apio', 'mostaza', 'sesamo', 'sulfitos', 'altramuces', 'moluscos');

CREATE TABLE IF NOT EXISTS public.categoria
(
    id serial NOT NULL,
    nombre character varying(40) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.item_pedido
(
    id serial NOT NULL,
    id_pedido integer NOT NULL,
    id_producto integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(6, 2) NOT NULL,
    cantidad integer NOT NULL,
    CONSTRAINT itempedido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id serial NOT NULL,
    localizador character varying(8) COLLATE pg_catalog."default" NOT NULL,
    fecha timestamp with time zone NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    apellidos character varying(30) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(150) COLLATE pg_catalog."default" NOT NULL,
    estado estado_pedido NOT NULL,
    comentario character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT pedido_pkey PRIMARY KEY (id),
    CONSTRAINT pedido_localizador_key UNIQUE (localizador)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id serial NOT NULL,
    id_categoria integer NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(6, 2) NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default",
    stock integer NOT NULL,
    foto character varying(300) COLLATE pg_catalog."default" NOT NULL,
    alergenos tipo_alergeno[] NOT NULL,
    CONSTRAINT producto_pkey PRIMARY KEY (id),
    CONSTRAINT producto_nombre_key UNIQUE (nombre)
);

ALTER TABLE IF EXISTS public.item_pedido
    ADD CONSTRAINT "itempedido_idPedido_fkey" FOREIGN KEY (id_pedido)
    REFERENCES public.pedido (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.item_pedido
    ADD CONSTRAINT "itempedido_idProducto_fkey" FOREIGN KEY (id_producto)
    REFERENCES public.producto (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.producto
    ADD CONSTRAINT "producto_idCategoria_fkey" FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
